# Generated by Django 5.1.5 on 2025-01-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, help_text='Digite apenas seu nome de usuário, sem @ (opcional)', max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Digite apenas números', max_length=20),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['user_type'], name='users_custo_user_ty_f25e6c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['cidade_ref'], name='users_custo_cidade__f33bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['estado_ref'], name='users_custo_estado__dea4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['plano'], name='users_custo_plano_21b455_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_vip'], name='users_custo_is_vip_42ff08_idx'),
        ),
    ]
