from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS users_acompanhanteprofile (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                nome_completo varchar(100) NOT NULL,
                foto varchar(100) NULL,
                whatsapp varchar(20) NULL,
                instagram varchar(50) NULL,
                biografia text NULL,
                created_at timestamp with time zone NOT NULL,
                updated_at timestamp with time zone NOT NULL,
                cidade_id bigint NULL REFERENCES users_cidade(id),
                estado_id bigint NULL REFERENCES users_estado(id),
                user_id bigint NOT NULL UNIQUE REFERENCES users_customuser(id)
            );
            """,
            "DROP TABLE IF EXISTS users_acompanhanteprofile CASCADE;"
        ),
    ] 