# Generated by Django 5.1.5 on 2025-01-19 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['-created_at'], name='ads_anuncio_created_9886f1_idx'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['status'], name='ads_anuncio_status_20ed02_idx'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['is_boosted'], name='ads_anuncio_is_boos_695108_idx'),
        ),
        migrations.AddIndex(
            model_name='anuncio',
            index=models.Index(fields=['categoria'], name='ads_anuncio_categor_7bc96e_idx'),
        ),
    ]
